#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/30a0ae31-81b1-494a-8c07-64dc85fe4124
title: ramal

protocols: [HTTP,HTTPS]

traits:
  errorResponse: !include traits/error Trait.raml

securitySchemes:
  securityCustomerScheme: !include security-scheme/securityScheme.raml
securedBy:
  - securityCustomerScheme

/accounts:
  post:
    is: [errorResponse]
    description: Create Account for customer
    body:
      application/xml:
        example: !include examples/account.json
    responses:
      201:
        body:
          application/json:
            example: !include examples/accountResp.json
                     
                  
  get:
    is: [errorResponse]
    description: Fetch account on basis of CustomerId
    queryParameters:
      customerId:
        type: string
        required: true
        example: "cust12345"
    responses:
      200:
        body:
          application/json:
            example: !include examples/account.json
           
                          
          
  
  /{accountId}:
    is: [errorResponse]
    get:
      description: Fetch single account
      responses:
        200:
          body:
            application/json:
              example: !include examples/account.json

    /balances:
      is: [errorResponse]
      get:
        description: 
        responses:
          200:
            body:
              application/json:
                example: !include examples/account.json
                  

    /transactions:
      is: [errorResponse]
      get:
        description: Fetch All Transactions
        queryParameters:
          formDate:
            type: string
            required: false
            example: "2021-12-14"
          toDate:
            type: string
            required: false
            example: "2021-12-30"
        responses:
          200:
            body:
              application/json:
                example: !include examples/transaction.json
                  
                              
              
      /{transactId}:
        is: [errorResponse]
        get:
          description: Fetch single transaction
          responses:
            200:
              body:
                application/json:
                  example: !include examples/transaction.json
                    

    
  